#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

if [ -f /etc/runmore.sh ]; then
	echo "About to run /etc/runmore.sh for you!"
	. /scripts/functions
	. /etc/runmore.sh
fi
